name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install obsidianhtml
      run: |
        pip install --upgrade pip
        pip install obsidianhtml
    - name: Deploy GitHub Pages
      run: |
        obsidianhtml convert -i tools/obsidianhtml.yml
        git worktree add gh-pages
        git config user.name "Deploy from CI"
        git config user.email ""
        cd gh-pages
        # Delete the ref to avoid keeping history.
        git update-ref -d refs/heads/gh-pages
        rm -rf *
        mv ../output/html/* .
        git add .
        git commit -m "Deploy  to gh-pages"
        git push --force --set-upstream origin gh-pages
